- id: prepend-jira-issue
  name: Prepend Jira Issue
  entry: prepend_jira_issue
  language: python
  description: This hook prepends a Jira issue to a commit message
  always_run: true
  stages: [commit-msg]
